# Actual Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: b00chat-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.org/client-max-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffering: 'on'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-methods: GET
    nginx.ingress.kubernetes.io/websocket-services: b00chat
spec:
  rules:
    - host: b00.inpt.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: b00chat
                port:
                  number: 3000

  tls:
    - hosts:
        - b00.inpt.fr
      secretName: b00chat-tls

---
# https://serverfault.com/a/1028704
# Redirection for people that'll type boo instead of b00
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: b00chat-redirect-from-boochat
  annotations:
    kubernetes.io/ingress.class: nginx
    # this should be covered by the annotation on the other ingress
    # since it will renew the same certificate
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/(.*)$ https://b00.inpt.fr/$1 permanent;
spec:
  rules:
    - host: boo.inpt.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: b00chat
                port:
                  number: 3000

  tls:
    - hosts:
        - boo.inpt.fr
      secretName: prod-tls
